name: Build and deploy to Azure WebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: appcmc2026-PS  # change for BS when needed
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          package: .
